#!/bin/bash

options="AlpineWiki\0icon\x1fdistributor-logo-alpine
AskBrave\0icon\x1fgnome-robots
Movix\0icon\x1fcom.github.artemanufrij.playmyvideos
ProtonDB\0icon\x1fdistributor-logo-steamos
Twitch\0icon\x1ftwitch-indicator
Youtube\0icon\x1fyoutube"

selection=$(echo -e "$options" | rofi -dmenu -show-icons -icon-theme "Papirus" -config ~/.config/rofi/web-menu.rasi)

if [[ -n "$selection" ]]; then
    case "$selection" in
        "AlpineWiki")
            firefox https://wiki.alpinelinux.org/wiki/Main_Page
            ;;
   		"AskBrave")
   		   	firefox https://search.brave.com/ask 
   		   	 ;;     
		"Movix")
			firefox https://movix.bet
			;;
        "ProtonDB")
            firefox https://www.protondb.com
            ;;
		"Twitch")
			firefox https://www.twitch.tv/directory
            ;;
        "Youtube")                    
            firefox https://www.youtube.com
             ;; 
    esac
fi   
